url: http://blog.thecityawards.com
port: 4000
source:         ./src
destination:    ./_site
plugins:        ./_plugins
tag_dir:        /tag
permalink:      /:title
sass:
  sass_dir: css
  style:  compressed
